// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ReilEgor/FinScale-backend/TransactionService/internal/config"
	"github.com/ReilEgor/FinScale-backend/TransactionService/internal/domain"
	"github.com/ReilEgor/FinScale-backend/TransactionService/internal/repository/postgres"
	"github.com/ReilEgor/FinScale-backend/TransactionService/internal/transport/rest"
	"github.com/ReilEgor/FinScale-backend/TransactionService/internal/transport/rest/handlers"
	"github.com/ReilEgor/FinScale-backend/TransactionService/internal/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, dsn config.DSN) (*App, func(), error) {
	pool, cleanup, err := postgres.NewPostgresRepository(ctx, dsn)
	if err != nil {
		return nil, nil, err
	}
	transactionRepository := postgres.NewTransactionRepository(pool)
	transactionUseCase := usecase.NewTransactionUseCase(transactionRepository)
	ginServer := rest.NewGinServer(transactionUseCase)
	app := &App{
		Logic:  transactionUseCase,
		Server: ginServer,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var UseCaseSet = wire.NewSet(usecase.NewTransactionUseCase, wire.Bind(new(domain.TransactionUseCase), new(*usecase.TransactionUseCase)))

var RepositorySet = wire.NewSet(postgres.NewPostgresRepository, postgres.NewTransactionRepository, wire.Bind(new(domain.TransactionRepository), new(*postgres.TransactionRepository)))

var RestSet = wire.NewSet(rest.NewGinServer, handlers.NewHandler)

type App struct {
	Logic  domain.TransactionUseCase
	Server *rest.GinServer
}
