// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyRepository is an autogenerated mock type for the CurrencyRepository type
type CurrencyRepository struct {
	mock.Mock
}

// GetCurrency provides a mock function with given fields: ctx, from, to
func (_m *CurrencyRepository) GetCurrency(ctx context.Context, from string, to string) (float64, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrency")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (float64, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) float64); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveCurrency provides a mock function with given fields: ctx, from, to, rate
func (_m *CurrencyRepository) SaveCurrency(ctx context.Context, from string, to string, rate float64) error {
	ret := _m.Called(ctx, from, to, rate)

	if len(ret) == 0 {
		panic("no return value specified for SaveCurrency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) error); ok {
		r0 = rf(ctx, from, to, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCurrencyRepository creates a new instance of CurrencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyRepository {
	mock := &CurrencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
